# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/b8080f-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter b8080f,$(TARGET_DEVICE)),)

endif
